# Generated by Django 4.2.16 on 2024-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.TextField(default='course'),
            preserve_default=False,
        ),
    ]
