# Generated by Django 4.2.16 on 2024-11-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='course',
            new_name='coursee',
        ),
    ]
